# Generated by Django 2.2 on 2019-05-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImportRaw', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labkey',
        ),
    ]
