# Generated by Django 2.2 on 2019-05-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('script', models.FileField(upload_to='Scripts')),
                ('params_list', models.FileField(upload_to='Scripts/Params')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputeGraph.AnalysisFamily')),
            ],
        ),
    ]
