# Generated by Django 2.2 on 2019-05-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImportRaw', '0001_initial'),
        ('ComputeGraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo4j_uri', models.URLField()),
                ('neo4j_user', models.CharField(default='neo4j', max_length=200)),
                ('neo4j_password', models.CharField(default='neo4j', max_length=200)),
                ('analysis_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputeGraph.AnalysisFamily')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImportRaw.RawData')),
            ],
        ),
    ]
