# Generated by Django 2.2 on 2019-05-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComputeGraph', '0002_graph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='params_list',
            new_name='parameters_json_file',
        ),
    ]
