# Generated by Django 2.2 on 2019-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputeGraph', '0004_auto_20190528_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='neo4j_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='neo4j_uri',
            new_name='uri',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='neo4j_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='graph',
            name='bolt_port',
            field=models.IntegerField(default=7687),
        ),
        migrations.AddField(
            model_name='graph',
            name='http_port',
            field=models.IntegerField(default=7474),
        ),
        migrations.AddField(
            model_name='graph',
            name='launcher',
            field=models.FilePathField(default='/usr/bin/neo4j'),
        ),
    ]
