# Generated by Django 2.2 on 2019-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputeGraph', '0005_auto_20190529_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='name',
            field=models.CharField(default='graph', max_length=500),
        ),
    ]
