# Generated by Django 2.2 on 2019-05-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputeGraph', '0006_graph_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='launcher',
            field=models.FilePathField(default='/usr/bin/neo4j', path='/'),
        ),
    ]
