# Generated by Django 2.2 on 2019-05-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputeGraph', '0007_auto_20190529_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='launcher',
            field=models.CharField(default='/usr/bin/neo4j', max_length=500),
        ),
    ]
