# Generated by Django 2.2 on 2019-05-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statlist',
            name='script',
            field=models.FilePathField(path='/home/jean_clement/'),
        ),
    ]
