# Generated by Django 2.2 on 2019-05-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_graph', '0002_auto_20190524_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statlist',
            name='script',
            field=models.FilePathField(path='/home/jean_clement/script_r'),
        ),
    ]
