# Generated by Django 2.2 on 2019-05-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_graph', '0003_auto_20190524_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='statlist',
            name='params_list',
            field=models.FilePathField(default='/home/jean_clement/script_r', path='/home/jean_clement/script_r'),
        ),
    ]
